proyecto/clientes/urls.py
from django.urls import path
from . import views

app_name = "clientes"


urlpatterns = [
    path("", views.index, name="index"),
    path("pais/list", views.pais_list, name="pais_list"),
    path("cliente/list", views.cliente_list, name="cliente_list"),
]

proyecto/home/urls.py
from django.urls import path
from . import views

app_name = "home"

urlpatterns = [
    path("", views.index, name="index"),
]

proyecto/proyecto/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
     path('', include('home.urls')),
    path('clientes/', include('clientes.urls')),
   
]

proyecto/clientes/models.py
from django.db import models

# Create your models here.

class Pais(models.Model):
    nombre = models.CharField(max_length=50)

    def __str__(self):
        return self.nombre   


class Cliente(models.Model):
    nombre = models.CharField(max_length=50)
    apellido = models.CharField(max_length=50)
    nacimiento = models.DateField(null=True, blank=True)
    pais_origen_id = models.ForeignKey(Pais, on_delete=models.SET_NULL, null=True, blank=True)

    def  __str__(self):
        return f"{self.apellido}, {self.nombre}"

proyecto/home/models.py
from django.db import models

# Create your models here.

proyecto/clientes/views.py
from django.shortcuts import render
from .models import Pais, Cliente

def index(request):
    return render(request, 'clientes/index.html')


def pais_list(request):
    paises = Pais.objects.all()
    return render(request, 'clientes/pais_list.html', {'paises': paises})  

def cliente_list(request):
    clientes = Cliente.objects.all()
    return render(request, 'clientes/cliente_list.html', {'clientes': clientes})  

proyecto/home/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    return render(request, 'home/index.html')

proyecto/clientes/templates/clientes/cliente_list.html
{% extends 'home/base.html' %}

{% block header %}
    Listado De clientes
{% endblock header %}

{% block main %}

    <ul>
        {% for cliente in clientes %}
            <li> Cliente es: {{cliente}}</li>
        {% endfor %}
    </ul>

    <button><a href="{% url 'clientes:index' %}">Back</a></button>
    
{% endblock main %}

proyecto/clientes/templates/clientes/index.html
{% extends 'home/base.html' %}

{% block header %}
    Clientes
{% endblock header %}

{% block main %}
<a href="{% url 'clientes:pais_list' %}">Listar Paises</a>
<a href="{% url 'clientes:cliente_list' %}">Listar Clientes</a>
{% endblock main %}

proyecto/clientes/templates/clientes/pais_list.html
{% extends 'home/base.html' %}

{% block header %}
    Paises
{% endblock header %}

{% block main %}

    <ul>
        {% for pais in paises %}
            <li>{{pais}}</li>
        {% endfor %}
    </ul>

|   <h2> </h2>

    <button><a href="{% url 'clientes:index' %}">Back</a></button>

{% endblock main %}

proyecto/home/templates/home/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Coderhouse</title>
</head>
<body>
    <header>
        <h1>
        {% block header %}    
        {% endblock header %}
    </h1>
    </header>

    <main>
        {% include 'home/componentes/navbar.html' %}
        {% block main %}
            
        {% endblock main %}
    </main>

    <footer>
        {% include 'home/componentes/footer.html' %}
    </footer>

</body>
</html>

proyecto/home/templates/home/componentes/footer.html
<p>
    Hecho por Dyangelo 2024
</p>

proyecto/home/templates/home/componentes/navbar.html
<navbar>
    <a href="{% url 'clientes:index' %}">App clientes</a>
    <button><a href="{% url 'home:index' %}">home</a></button>
</navbar>

proyecto/home/templates/home/index.html
{% extends 'home/base.html' %}


{% block header %}
   Proyecto
{% endblock header %}

{% block main %}
    
{% endblock main %}